void Recorderdata() {
  if (statusstartrec) {
    status_rec = "       Recording";

    if (setparametersdata == 1) {
      initializeRecording();
    }

      if (millis() - lastTimeUpdate_dt >= timePerRecord_dt) {
      recordData();
      lastTimeUpdate_dt = millis();
    }
  }
}

void initializeRecording() {
  setparametersdata = 0;
  Userinfo = " - Data recording started";
  
  timePerRecord_dt = (1000 * float(getConfigurationString("savedata")));

  String logMessage = year() + "/" + month() + "/" + day() + "_" + hour() + ":" + minute() + ":" + second() + " - Started collecting analytical data by ";
  logMessage += (dotre == 0) ? "manual command.  // " : "external command.  // ";
  logMessage += datamoment + "\r\n/\r\n";
  oldlogs += logMessage;
  dotre = 0;

  datasout += "Report generated by SD Plotter DB - Version " + rev + "\r\n" +
    "Acquired by " + username + "\r\n" +
    "Machine Code: " + keyinopen + "\r\n" +
    "Serial Number: SD" + getConfigurationString("serialnumber") + "\r\n" +
    "Settings:;" + float(getConfigurationString("savedata")) + "\r\n" +
    "Number;Year;Month;Day;Hour;Minute;Second;" +
    getConfigurationString("sensor1") + ";" +
    getConfigurationString("sensor2") + ";" +
    getConfigurationString("sensor3") + ";" +
    getConfigurationString("sensor4") + ";" +
    getConfigurationString("sensor5") + ";" +
    getConfigurationString("sensor6") + ";" +
    getConfigurationString("sensor7") + ";" +
    getConfigurationString("sensor8") + ";\r\n" +
    "; ; ; ; ; ; ;" +
    getConfigurationString("unit1") + ";" +
    getConfigurationString("unit2") + ";" +
    getConfigurationString("unit3") + ";" +
    getConfigurationString("unit4") + ";" +
    getConfigurationString("unit5") + ";" +
    getConfigurationString("unit6") + ";" +
    getConfigurationString("unit7") + ";" +
    getConfigurationString("unit8") + ";\r\n";
}

void recordData() {
  numberbt++;
  
  String dataLine = numberbt + ";" + year() + ";" + month() + ";" + day() + ";" + hour() + ";" + minute() + ";" + second() + ";";
  if (modeunit) {
    dataLine += rawvalues[0] + ";" + rawvalues[1] + ";" + rawvalues[2] + ";" + rawvalues[3] + ";" + rawvalues[4] + ";" + rawvalues[5] + ";" + rawvalues[6] + ";" + rawvalues[7] + ";\r\n";
  } else {
    dataLine += raw[0] + ";" + raw[1] + ";" + raw[2] + ";" + raw[3] + ";" + raw[4] + ";" + raw[5] + ";" + raw[6] + ";" + raw[7] + ";\r\n";
  }

  datasout += dataLine;
}

void Createmethod() {
  if (statusok && reccontrol) {
    if (millis() - lastTimeUpdate_cr >= timePerRecord_cr) {
      methodout += (str(tptemp) + ";" + str(mttemp) + ";" + str(c) + ";" + str(d) + ";0\r\n");
     lastTimeUpdate_cr = millis();
    }
  }
}

void Loadmethod() {
  handleExternalCommand();
  handleMethodPlaybackStart();
  handleMethodReproductionCompletion();
  handleMethodPlaybackStop();
  handleStartControl();
}

void handleExternalCommand() {
  if (dotrwe == 1) {
    logEvent(" - Received external command to start method.");
    Userinfo = " - Started Method Reproduction";
    status_met = "  Started Method";
    dotrwe = 0;
  }
}

void handleMethodPlaybackStart() {
  if (dotr == 1) {
    logEvent(" - Method playback started. // " + numberfile);
    Userinfo = " - Started Method Reproduction";
    status_met = "  Started Method";

    resetMethodTimers();
    refreshmethod = true;
    dotr = 0;
  }
}

void handleMethodReproductionCompletion() {
  if (dotp == 1) {
    logEvent(" - Method reproduction completion. // " + numberfile);
    dotp = 0;
  }
}

void handleMethodPlaybackStop() {
  if (dotpu == 1) {
    logEvent(" - Method playback stopped. // " + numberfile);
    Userinfo = " - Stop method playback";
    status_met = "   Stop recording";
    dotpu = 0;
  }
}

void handleStartControl() {
  
    if (startcontrol && millis() - lastTimeUpdate_pl >= timePerRecord_pl) {
    String[] plust1 = split(myStringsmet[imet], ";");
    imet = (imet + 1) % myStringsmet.length;
    lastTimeUpdate_pl = millis();
    tptemp = int(plust1[0]);
    mttemp = int(plust1[1]);
    c = int(plust1[2]);
    d = int(plust1[3]);

    if (int(plust1[4]) == 1) {
      endMethod();
    }
  }
}

void resetMethodTimers() {
  lastTimeUpdate_pl = 0;
  millisecs2 = seconds2 = minutes2 = hour2 = day2 = 0;
  imet = 0;
}

void endMethod() {
  startcontrol = false;
  dotp = 1;
  cp1.getController("startcontrol").setValue(0);
  Userinfo = " - Method is over";
  status_met = "   Method is over";
}
